// Generated by CodiumAI

describe('Navbar_function', () => {

});

    // Tests that the Navbar component renders without crashing
    it('test_navbar_renders_without_crashing', () => {
        // Test code here
    });


    // Tests that the Navbar component displays the logo
    it('test_navbar_displays_logo', () => {
        // Arrange
        const wrapper = shallow(<Navbar />);

        // Act
        const logo = wrapper.find('img');

        // Assert
        expect(logo.prop('src')).toEqual('../images/logo.png');
    });


    // Tests that the active link is highlighted on scroll
    it('test_navbar_highlight_active_link_on_scroll', () => {
        // Simulate scroll event
        const scrollEvent = new Event('scroll');
        window.dispatchEvent(scrollEvent);

        // Check if the active link is highlighted
        const activeLinkElement = document.querySelector('.nav-link.active');
        expect(activeLinkElement).not.toBeNull();
    });

